{{- if eq (include "atlas.createSecret" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atlas.secretName" . }}
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.atlas.auth.enabled (not .Values.atlas.auth.existingSecret) .Values.atlas.auth.password }}
  {{ .Values.atlas.auth.usernameKey }}: {{ .Values.atlas.auth.username | quote }}
  {{ .Values.atlas.auth.passwordKey }}: {{ .Values.atlas.auth.password | quote }}
  {{- end }}
  {{- if and .Values.atlas.vault.enabled (not .Values.atlas.vault.existingSecret) .Values.atlas.vault.key }}
  {{ .Values.atlas.vault.keyKey }}: {{ .Values.atlas.vault.key | quote }}
  {{- end }}
{{- end }}
