package feed

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The feed generator (ADR-draft-whats-new-in-go).
//
// It replaced a script in another language, and the output is a committed file CI
// regenerates to check the commit is current — so the property that matters most
// is not that the feed is *reasonable* but that it is **the same bytes**. That one
// is held where it can be: the repository's own feed, regenerated by the guard in
// api/whatsnew_test.go.
//
// What is held here is the set of rules that file is made of, each of which has a
// way of being wrong that no diff would explain.

// tree builds a throwaway repository layout and returns its paths.
func tree(t *testing.T, changelog string, overrides map[string]string) Paths {
	t.Helper()
	root := t.TempDir()
	for _, dir := range []string{
		filepath.Join(root, "api", "web"),
		filepath.Join(root, "docs", "adr"),
		filepath.Join(root, "scripts", "whats-new", "overrides"),
	} {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			t.Fatal(err)
		}
	}
	p := PathsUnder(root)
	if err := os.WriteFile(p.Changelog, []byte(changelog), 0o600); err != nil {
		t.Fatal(err)
	}
	for name, body := range overrides {
		if err := os.WriteFile(filepath.Join(p.Overrides, name), []byte(body), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	return p
}

const unknownRecord = "ADR-" + "9999"

const oneBullet = "# Changelog\n\n## [0.9.0] — 2026-03-04\n\n### Added\n\n" +
	"- **A thing happened.** And here is what it means. A second sentence.\n"

// TestTheIdIsTheRuleTheOverrideFilesAreNamedBy.
//
// 259 curated files are named by this slug. A port that folded a character
// differently, or cut at a different length, would orphan every file whose name it
// changed — and an orphaned override is an entry rendering from the CHANGELOG's own
// wording, which looks exactly like one nobody has curated yet.
func TestTheIdIsTheRuleTheOverrideFilesAreNamedBy(t *testing.T) {
	for _, c := range []struct{ in, want string }{
		{"A thing happened.", "a-thing-happened"},
		{"Two   spaces, and punctuation!", "two-spaces-and-punctuation"},
		{"---leading and trailing---", "leading-and-trailing"},
		{"Grösse und Größe", "gr-sse-und-gr-e"},
		{"MiXeD CaSe", "mixed-case"},
		{"", ""},
		{"...", ""},
		// Cut at sixty, and the cut is not re-trimmed: a dash may survive at the end,
		// exactly as slice(0, 60) leaves one.
		{strings.Repeat("ab ", 30), strings.Repeat("ab-", 20)},
	} {
		if got := slugify(c.in); got != c.want {
			t.Errorf("slugify(%q) = %q, want %q", c.in, got, c.want)
		}
	}
	if got := slugify(strings.Repeat("x", 80)); len(got) != 60 {
		t.Errorf("a long headline yields %d characters, want 60", len(got))
	}
}

// TestTheFallbackSummaryIsOneSentenceOfPlainProse.
//
// It is what an entry reads as when nobody has curated it, so it has to be
// readable on its own: markdown gone, one sentence, no trailing half of a second.
func TestTheFallbackSummaryIsOneSentenceOfPlainProse(t *testing.T) {
	for _, c := range []struct{ in, want string }{
		{"And here is what it means. A second sentence.", "And here is what it means."},
		{"A [linked](docs/x.md) word stays a word.", "A linked word stays a word."},
		{"`code` and *emphasis* and _underscores_ go.", "code and emphasis and underscores go."},
		{"No sentence end at all", "No sentence end at all"},
		{"Line\nbreaks  collapse.", "Line breaks collapse."},
	} {
		if got := firstSentence(c.in); got != c.want {
			t.Errorf("firstSentence(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

// TestAnEntryPointsAtTheMostUserFacingThingItNames.
//
// A pull request first, because that is what a reader can act on; then a record;
// and failing both, the version's own section, so that no entry is a dead end.
func TestAnEntryPointsAtTheMostUserFacingThingItNames(t *testing.T) {
	paths := map[string]string{"0158": "docs/adr/0158-something.md"}
	for _, c := range []struct{ name, block, wantLabel, wantURL string }{
		{"a pull request wins over a bare record", "- **X.** (#42) and ADR-0158",
			"PR #42", repoURL + "/pull/42"},
		// And over a spelled-out one. The first version of this table only had the
		// bare case, so swapping the two checks in the source changed nothing here —
		// the precedence was asserted for one of the two records it ranks above.
		{"a pull request wins over a spelled-out record",
			"- **X.** (#42) and [ADR-0158](docs/adr/0158-something.md)",
			"PR #42", repoURL + "/pull/42"},
		{"a spelled-out record", "- **X.** [ADR-0158](docs/adr/0158-something.md)",
			"ADR-0158", blobURL + "/docs/adr/0158-something.md"},
		{"a bare record resolves from the directory", "- **X.** as ADR-0158 has it",
			"ADR-0158", blobURL + "/docs/adr/0158-something.md"},
		// Assembled rather than written out: a record number in this file is a
		// citation like any other, and the guard that checks every citation resolves
		// would read a made-up one as a broken link to a record nobody wrote.
		{"a bare record nothing knows", "- **X.** as " + unknownRecord + " has it",
			unknownRecord, blobURL + "/docs/adr"},
		{"nothing named", "- **X.** plain prose", "Changelog", blobURL + "/CHANGELOG.md#0-9-0"},
	} {
		got := linkFor(c.block, paths, "0-9-0")
		if got.Label != c.wantLabel || got.URL != c.wantURL {
			t.Errorf("%s: %+v, want %s %s", c.name, got, c.wantLabel, c.wantURL)
		}
	}
}

// TestGermanFallsBackToEnglishAndNeverToNothing.
//
// The feed is bilingual with a per-visitor toggle, so an entry with no German is
// an entry that renders empty in German. Falling back is what keeps the toggle
// from being a way to blank the page.
func TestGermanFallsBackToEnglishAndNeverToNothing(t *testing.T) {
	p := tree(t, oneBullet, map[string]string{
		"a-thing-happened.json": `{"summary":{"en":"Only English"}}`,
	})
	doc, err := Build(p)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	if len(doc.Entries) != 1 {
		t.Fatalf("%d entries, want 1", len(doc.Entries))
	}
	e := doc.Entries[0]
	if e.Summary.DE != "Only English" {
		t.Errorf("German summary = %q, want the English one", e.Summary.DE)
	}
	// And a title nobody overrode is the CHANGELOG's own, in both languages.
	if e.Title.EN != "A thing happened." || e.Title.DE != e.Title.EN {
		t.Errorf("title = %+v", e.Title)
	}
	if e.Summary.EN != "Only English" {
		t.Errorf("English summary = %q", e.Summary.EN)
	}
}

// TestAnOverrideKeyThatMatchesNothingIsAMistakeAndSaysSo.
//
// A key matching no bullet does nothing at all, and the entry still renders — from
// the CHANGELOG's own wording, with German falling back to English. That is
// indistinguishable from "nobody wrote an override", so a mistyped key ships an
// untranslated entry in silence. One did.
func TestAnOverrideKeyThatMatchesNothingIsAMistakeAndSaysSo(t *testing.T) {
	p := tree(t, oneBullet, map[string]string{
		"a-thing-happened.json":     `{"summary":"fine"}`,
		"a-thing-that-did-not.json": `{"summary":"orphan"}`,
	})
	_, err := Build(p)
	if err == nil {
		t.Fatal("an override matching no bullet was accepted")
	}
	if !strings.Contains(err.Error(), "a-thing-that-did-not") {
		t.Errorf("the refusal does not name the key: %v", err)
	}
	// A key beginning with an underscore is a note rather than an entry, and is not
	// held to this.
	p = tree(t, oneBullet, map[string]string{
		"a-thing-happened.json": `{"summary":"fine"}`,
		"_notes.json":           `{"summary":"a note to a maintainer"}`,
	})
	if _, err := Build(p); err != nil {
		t.Errorf("a note was treated as an orphan: %v", err)
	}
}

// TestAKeyThatDoesNothingIsRefusedRatherThanIgnored.
//
// The rule one level down from the orphan check, and it was earned: an override
// carried `route` at the top level instead of inside `try`, so its deep link did
// nothing and nothing anywhere said so. A key that does nothing is
// indistinguishable from a key nobody wrote.
func TestAKeyThatDoesNothingIsRefusedRatherThanIgnored(t *testing.T) {
	p := tree(t, oneBullet, map[string]string{
		"a-thing-happened.json": `{"summary":"fine","route":"#/console/workers"}`,
	})
	_, err := Build(p)
	if err == nil {
		t.Fatal("an override with a key that does nothing was accepted")
	}
	if !strings.Contains(err.Error(), "route") {
		t.Errorf("the refusal does not name the key: %v", err)
	}
}

// TestHiddenEntriesAndTheCap.
//
// Hidden is how a purely internal bullet stays out of a user-facing list; the cap
// is what keeps the list compact. Both drop entries, and a drop that took the
// wrong one would be invisible in a feed that still looks well-formed.
func TestHiddenEntriesAndTheCap(t *testing.T) {
	var b strings.Builder
	b.WriteString("# Changelog\n\n## [1.0.0] — 2026-05-05\n\n### Added\n\n")
	for i := 0; i < MaxEntries+3; i++ {
		b.WriteString("- **Entry ")
		b.WriteByte(byte('a' + i))
		b.WriteString(".** Prose.\n")
	}
	p := tree(t, b.String(), map[string]string{"entry-a.json": `{"hidden":true}`})
	doc, err := Build(p)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	if len(doc.Entries) != MaxEntries {
		t.Fatalf("%d entries, want the cap of %d", len(doc.Entries), MaxEntries)
	}
	if doc.Entries[0].ID != "entry-b" {
		t.Errorf("the first entry is %q; the hidden one was not dropped", doc.Entries[0].ID)
	}
	// The stamp is the newest dated section and never the clock: the output is
	// committed and re-generated by CI to check the commit is current, so a
	// wall-clock stamp would fail that check on the date alone.
	if doc.GeneratedAt == nil || *doc.GeneratedAt != "2026-05-05" {
		t.Errorf("generatedAt = %v, want the newest dated section", doc.GeneratedAt)
	}
}

// TestTheEncodingIsTheOneTheFeedWasWrittenIn.
//
// Two settings carry byte-compatibility with the JavaScript this replaced, and
// both are defaults in Go that point the other way. Losing either changes
// thousands of bytes and fails the staleness check on prose alone.
func TestTheEncodingIsTheOneTheFeedWasWrittenIn(t *testing.T) {
	p := tree(t, "# Changelog\n\n## [1.0.0] — 2026-05-05\n\n### Added\n\n"+
		"- **Angle < brackets & ampersands.** They survive.\n", nil)
	doc, err := Build(p)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	out, err := Encode(doc)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}
	// The needles are built rather than written as literals. A "\\u003c" spelled out
	// in source is exactly the thing this asserts is absent, and a tool that
	// normalised the escape on its way into the file would turn the guard into a
	// search for "<" — which the output does contain, so it would pass by finding
	// the very thing it is meant to forbid. Building them from the digits cannot be
	// normalised.
	esc := func(hex string) string { return "\\u" + hex }
	if strings.Contains(string(out), esc("003c")) || strings.Contains(string(out), esc("0026")) {
		t.Error("the encoder escaped HTML; JavaScript's did not, so every such entry differs")
	}
	if !strings.HasSuffix(string(out), "}\n") {
		t.Errorf("the output does not end in a newline: %q", out[len(out)-10:])
	}
	if !strings.Contains(string(out), "\n  \"entries\": [") {
		t.Error("the output is not indented with two spaces")
	}
	// Key order is the wire contract, and Go writes struct fields in declaration
	// order — so a field moved for tidiness would change every byte after it.
	var keys []string
	dec := json.NewDecoder(strings.NewReader(string(out)))
	for {
		tok, err := dec.Token()
		if err != nil {
			break
		}
		if s, ok := tok.(string); ok && (s == "id" || s == "version" || s == "date" ||
			s == "category" || s == "title" || s == "summary" || s == "link") {
			keys = append(keys, s)
			if len(keys) == 7 {
				break
			}
		}
	}
	want := []string{"id", "version", "date", "category", "title", "summary", "link"}
	for i := range want {
		if i >= len(keys) || keys[i] != want[i] {
			t.Fatalf("entry key order = %v, want %v", keys, want)
		}
	}
}

// TestAConflictedSourceIsRefusedByThePackageThatReadsIt.
//
// The rule lives here because the reading does. api/whatsnew_test.go holds the
// same refusal end to end, and the first version of this file left it only there —
// so breaking the check inside this package kept every test in it green, which is
// how a guard comes to be held only by somebody else's suite.
func TestAConflictedSourceIsRefusedByThePackageThatReadsIt(t *testing.T) {
	const conflicted = "# Changelog\n\n## [Unreleased]\n\n### Added\n\n" +
		"<<<<<<< HEAD\n- **One side.** A.\n=======\n- **The other side.** B.\n>>>>>>> origin/main\n"
	p := tree(t, conflicted, nil)
	if _, err := Build(p); err == nil {
		t.Fatal("a conflicted CHANGELOG was accepted; both sides would become entries")
	} else if !strings.Contains(err.Error(), "unresolved merge conflicts") {
		t.Errorf("the refusal does not say why: %v", err)
	}

	// An override in the same state, for the same reason: it would fail the decode
	// anyway, but as a syntax error about an unexpected '<' — which sends the reader
	// looking for a typo rather than for the merge they are in the middle of.
	p = tree(t, oneBullet, map[string]string{
		"a-thing-happened.json": "<<<<<<< HEAD\n{\"summary\":\"A\"}\n=======\n{\"summary\":\"B\"}\n>>>>>>> origin/main\n",
	})
	if _, err := Build(p); err == nil {
		t.Fatal("a conflicted override was accepted")
	} else if !strings.Contains(err.Error(), "unresolved merge conflicts") {
		t.Errorf("the override's refusal does not say why: %v", err)
	}
}
