package eventcatalog

// Entries is the catalogue. An entry lands with the change that emits it: the drift
// tests refuse an entry nothing produces, and an emitted event no entry describes.
var Entries = []Entry{
	{
		Type:    "atlas.order.placed",
		Kind:    Domain,
		Meaning: "An order was placed; the fulfilment process starts working it.",
		Moments: []Moment{{
			Process: "atlas-auftrag-erfuellung", Element: "Start",
			Source: "the order service publishes it when it stores a new order; the fulfilment repair publishes it again for an order nothing works",
		}},
		Channels: []Channel{Message},
		Payload: []Field{
			{Name: "orderId", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The order, also the message's correlation key."},
			{Name: "orderer", Type: "string", Presence: Always, Personal: PersonalData,
				Meaning: "The principal id of the person who placed the order."},
			{Name: "recipient", Type: "string", Presence: Always, Personal: PersonalData,
				Meaning: "The principal id of the person the order is for."},
			{Name: "portalBaseUrl", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The installation's external address, empty where none is set."},
			{Name: "atlasApiBase", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The address the system processes call Atlas's own API at."},
		},
		SecretGuard: "api.TestOrderMessagesCarryTheirCataloguedPayload",
		Since:       "0.7.0",
		Stability:   Experimental,
	},
	{
		Type:    "atlas.order.advanced",
		Kind:    Domain,
		Meaning: "A position of an order settled; the fulfilment process asks what may start next.",
		Moments: []Moment{{
			Process: "atlas-auftrag-erfuellung", Element: "Warten",
			Source: "the order service publishes it when a position settles; a cancellation publishes it too",
		}},
		Channels:    []Channel{Message},
		SecretGuard: "api.TestOrderMessagesCarryTheirCataloguedPayload",
		Since:       "0.7.0",
		Stability:   Experimental,
	},
	{
		Type:    "<message>.<outcome>",
		Shape:   true,
		Kind:    Domain,
		Meaning: "An action on an order position reached an outcome. The product declares the name; without a declaration it is the action's message and the outcome.",
		Moments: []Moment{{
			Source: "the action outcome record (VTActionOutcome), folded into the feed as FeedOutcome (ADR-0429 §5)",
		}},
		Channels: []Channel{Feed},
		Payload: []Field{
			{Name: "orderId", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The order."},
			{Name: "position", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The position within the order."},
			{Name: "commandId", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The command the outcome answers."},
			{Name: "action", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The action's key."},
			{Name: "effect", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "What the action does to the right."},
			{Name: "outcome", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The outcome reached."},
			{Name: "source", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "Who reported the outcome."},
			{Name: "principal", Type: "string", Presence: Always, Personal: PersonalData,
				Meaning: "The principal id of the person the right belongs to."},
			{Name: "itemId", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The product."},
			{Name: "at", Type: "timestamp", Presence: Always, Personal: NotPersonal,
				Meaning: "When the outcome was recorded."},
			{Name: "variantId", Type: "string", Presence: Optional, Personal: NotPersonal,
				Meaning: "The product variant, where the product has variants."},
			{Name: "instanceKey", Type: "number", Presence: Optional, Personal: NotPersonal,
				Meaning: "The process instance that reported the outcome."},
			{Name: "result", Type: "json", Presence: Optional, Personal: NotPersonal,
				Meaning: "The result the action declared, where it returned one."},
			{Name: "homeCatalog", Type: "string", Presence: Optional, Personal: NotPersonal,
				Meaning: "The service catalogue that maintains the product (ADR-0432)."},
		},
		SecretGuard: "api.TestFeedTypesAreCatalogued",
		Since:       Unreleased,
		Stability:   Stable,
	},
	{
		Type:    "atlas.entitlement.granted",
		Kind:    Platform,
		Meaning: "A person was granted a right to a product.",
		Moments: []Moment{{
			Source: "the entitlement record (VTEntitlement), folded into the feed as FeedGranted (ADR-0429 §5)",
		}},
		Channels: []Channel{Feed},
		Payload: []Field{
			{Name: "principal", Type: "string", Presence: Always, Personal: PersonalData,
				Meaning: "The principal id of the person who holds the right."},
			{Name: "itemId", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The product."},
			{Name: "orderId", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The order the right came from, empty for an adopted right."},
			{Name: "since", Type: "timestamp", Presence: Always, Personal: NotPersonal,
				Meaning: "When the right began."},
			{Name: "origin", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "How the right came about."},
			{Name: "variantId", Type: "string", Presence: Optional, Personal: NotPersonal,
				Meaning: "The product variant, where the product has variants."},
			{Name: "until", Type: "timestamp", Presence: Optional, Personal: NotPersonal,
				Meaning: "When the right ends, where it is limited."},
			{Name: "homeCatalog", Type: "string", Presence: Optional, Personal: NotPersonal,
				Meaning: "The service catalogue that maintains the product (ADR-0432)."},
		},
		SecretGuard: "api.TestFeedTypesAreCatalogued",
		Since:       Unreleased,
		Stability:   Stable,
	},
	{
		Type:    "atlas.entitlement.revoked",
		Kind:    Platform,
		Meaning: "A person's right to a product ended.",
		Moments: []Moment{{
			Source: "the ended entitlement record (VTEntitlementHistory), folded into the feed as FeedRevoked (ADR-0429 §5)",
		}},
		Channels: []Channel{Feed},
		Payload: []Field{
			{Name: "principal", Type: "string", Presence: Always, Personal: PersonalData,
				Meaning: "The principal id of the person who held the right."},
			{Name: "itemId", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The product."},
			{Name: "orderId", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The order the right came from, empty for an adopted right."},
			{Name: "since", Type: "timestamp", Presence: Always, Personal: NotPersonal,
				Meaning: "When the right began."},
			{Name: "endedAt", Type: "timestamp", Presence: Always, Personal: NotPersonal,
				Meaning: "When the right ended."},
			{Name: "reason", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "Why the right ended."},
			{Name: "endedBy", Type: "string", Presence: Always, Personal: PersonalData,
				Meaning: "The principal id of who decided, empty where nothing recorded it."},
			{Name: "variantId", Type: "string", Presence: Optional, Personal: NotPersonal,
				Meaning: "The product variant, where the product has variants."},
			{Name: "homeCatalog", Type: "string", Presence: Optional, Personal: NotPersonal,
				Meaning: "The service catalogue that maintains the product (ADR-0432)."},
		},
		SecretGuard: "api.TestFeedTypesAreCatalogued",
		Since:       Unreleased,
		Stability:   Stable,
	},
	{
		Type:    "atlas.user.requested",
		Kind:    Domain,
		Meaning: "Somebody asked for an Atlas account; the request now waits for an administrator to approve it.",
		Moments: []Moment{{
			Process: "proc_benutzer_aufnahme", Element: "beantragt_melden",
		}},
		Channels: []Channel{Signal},
		Payload: []Field{
			{Name: "vorname", Type: "string", Presence: Always, Personal: PersonalData,
				Meaning: "The requester's first name."},
			{Name: "nachname", Type: "string", Presence: Always, Personal: PersonalData,
				Meaning: "The requester's last name."},
			{Name: "email", Type: "string", Presence: Always, Personal: PersonalData,
				Meaning: "The requester's mail address."},
			{Name: "abteilung", Type: "string", Presence: Optional, Personal: PersonalData,
				Meaning: "The requester's department or team."},
			{Name: "begruendung", Type: "string", Presence: Optional, Personal: PersonalData,
				Meaning: "Why the requester needs the account, as they wrote it."},
			{Name: "benutzername", Type: "string", Presence: Always, Personal: PersonalData,
				Meaning: "The username proposed for the account."},
			{Name: "atlasInstance", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The intake process instance, to point back at the request."},
		},
		SecretGuard: "api.TestSystemIntakeAnnouncesTheRequestAsASignal",
		Since:       Unreleased,
		Stability:   Experimental,
	},
	{
		Type:    "atlas.approval.requested",
		Kind:    Domain,
		Meaning: "An order position needs an approval; the approval task now waits for the approver.",
		Moments: []Moment{
			{Process: "atlas-genehmigung-fix", Element: "Angefragt"},
			{Process: "atlas-genehmigung-rolle", Element: "Angefragt"},
			{Process: "atlas-genehmigung-vorgesetzter", Element: "Angefragt"},
		},
		Channels: []Channel{Signal},
		Payload: []Field{
			{Name: "orderId", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The order."},
			{Name: "itemId", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The product the position orders."},
			{Name: "positionId", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The position within the order."},
			{Name: "variantId", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The product variant, empty where the product has none."},
			{Name: "orderer", Type: "string", Presence: Always, Personal: PersonalData,
				Meaning: "The principal id of the person who placed the order."},
			{Name: "recipient", Type: "string", Presence: Always, Personal: PersonalData,
				Meaning: "The principal id of the person the position is for."},
			{Name: "approvalRef", Type: "string", Presence: Always, Personal: PersonalData,
				Meaning: "Who approves, as the product names it: a person, or a role."},
			{Name: "vorgesetzter", Type: "string", Presence: Optional, Personal: PersonalData,
				Meaning: "The orderer's line manager, read from the directory; only where the product asks its superior to approve."},
			{Name: "provisionProcess", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The process that provisions the position once it is approved."},
			{Name: "atlasApiBase", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The address the system processes call Atlas's own API at."},
			{Name: "portalBaseUrl", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The installation's external address, empty where none is set."},
			{Name: "atlasInstance", Type: "string", Presence: Always, Personal: NotPersonal,
				Meaning: "The approval process instance, to point back at the request."},
		},
		SecretGuard: "api.TestApprovalAnnouncesTheRequestAsASignal",
		Since:       Unreleased,
		Stability:   Experimental,
	},
}
