package eventcatalog

import (
	"fmt"
	"html"
	"strings"
)

// The documentation is generated from the catalogue, never written beside it
// (ADR-0435 §5): the handbook's chapter and the runtime contract's table are the
// entries rendered, and `go test ./eventcatalog -update` writes them. A test fails
// when either has fallen behind.

// Markers delimit what is generated in a document; what lies outside them is prose.
const (
	HandbookBegin = "<!-- eventcatalog:begin (generated by go test ./eventcatalog -update) -->"
	HandbookEnd   = "<!-- eventcatalog:end -->"
	ContractBegin = "<!-- eventcatalog:feed:begin (generated by go test ./eventcatalog -update) -->"
	ContractEnd   = "<!-- eventcatalog:feed:end -->"
)

// HandbookHTML renders every entry for the handbook's chapter, in both languages.
func HandbookHTML() string {
	var b strings.Builder
	esc := html.EscapeString
	for _, e := range Entries {
		fmt.Fprintf(&b, "      <h3 id=\"ev-%s\"><code>%s</code></h3>\n", anchor(e.Type), esc(e.Type))
		fmt.Fprintf(&b, "      <p data-l=\"de\">%s</p>\n      <p data-l=\"en\">%s</p>\n", esc(e.Meaning.DE), esc(e.Meaning.EN))
		channels := make([]string, 0, len(e.Channels))
		for _, c := range e.Channels {
			channels = append(channels, string(c))
		}
		where := esc(e.Moment.Producer)
		if len(e.Moment.Places) > 0 {
			places := make([]string, 0, len(e.Moment.Places))
			for _, pl := range e.Moment.Places {
				places = append(places, "<code>"+esc(pl.Process)+"</code> / <code>"+esc(pl.Element)+"</code>")
			}
			where = strings.Join(places, ", ") + " — " + where
		}
		fmt.Fprintf(&b, "      <p class=\"muted\"><span data-l=\"de\">Art</span><span data-l=\"en\">Kind</span>: %s · "+
			"<span data-l=\"de\">Kanäle</span><span data-l=\"en\">Channels</span>: %s · "+
			"<span data-l=\"de\">seit</span><span data-l=\"en\">since</span> %s · %s<br>%s</p>\n",
			esc(string(e.Kind)), esc(strings.Join(channels, ", ")), esc(e.Since), esc(string(e.Stability)), where)
		if len(e.Payload) == 0 {
			b.WriteString("      <p class=\"muted\"><span data-l=\"de\">Ohne Felder: Das Ereignis ist sein Name.</span>" +
				"<span data-l=\"en\">No fields: the event is its name.</span></p>\n")
			continue
		}
		b.WriteString("      <table>\n        <thead><tr><th data-l=\"de\">Feld</th><th data-l=\"en\">Field</th>" +
			"<th data-l=\"de\">Typ</th><th data-l=\"en\">Type</th><th></th><th data-l=\"de\">Bedeutung</th><th data-l=\"en\">Meaning</th></tr></thead>\n        <tbody>\n")
		for _, f := range e.Payload {
			marks := ""
			if !f.Always {
				marks = "<span data-l=\"de\">optional</span><span data-l=\"en\">optional</span>"
			}
			if f.Personal() {
				if marks != "" {
					marks += " · "
				}
				marks += "<span data-l=\"de\">Personendaten</span><span data-l=\"en\">personal data</span>"
			}
			fmt.Fprintf(&b, "          <tr><td><code>%s</code></td><td>%s</td><td>%s</td><td data-l=\"de\">%s</td><td data-l=\"en\">%s</td></tr>\n",
				esc(f.Name), esc(f.Type), marks, esc(f.Meaning.DE), esc(f.Meaning.EN))
		}
		b.WriteString("        </tbody>\n      </table>\n")
	}
	return b.String()
}

// ContractTable renders the feed's event types for docs/runtime-contract.md.
func ContractTable() string {
	var b strings.Builder
	b.WriteString("| Type | Meaning | Since | Stability |\n|---|---|---|---|\n")
	for _, e := range Entries {
		if !e.Has(Feed) {
			continue
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", e.Type, strings.ReplaceAll(e.Meaning.EN, "|", "\\|"), e.Since, e.Stability)
	}
	return b.String()
}

// anchor is an id for a heading, from an event type.
func anchor(t string) string {
	r := strings.NewReplacer(".", "-", "<", "", ">", "")
	return r.Replace(t)
}

// Splice puts generated text between a document's markers, and reports whether the
// document carries them.
func Splice(doc, begin, end, generated string) (string, bool) {
	i := strings.Index(doc, begin)
	j := strings.Index(doc, end)
	if i < 0 || j < i {
		return doc, false
	}
	return doc[:i+len(begin)] + "\n" + generated + doc[j:], true
}
